version: '3.8'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development